import type { ThreadComment, ThreadData } from "@/types";
import { buildHeader, buildSidebar } from "./shared";

const baseThread: ThreadData = {
  id: "help-001",
  category: "help",
  header: buildHeader({
    category: "help",
    title: "Need help: Next.js streaming mismatch with AI output hydration",
    authorId: "u2",
    tags: ["Help", "Next.js 14", "Hydration"],
    views: 13190,
    upvotes: 402,
    bookmarks: 211,
  }),
  bodyMarkdown:
    "I’m building a discussion assistant with streamed model output and seeing intermittent hydration mismatch after suspense boundaries resolve. Repro is consistent in dev but rare in production build.",
  sidebar: { aboutAuthor: { authorId: "u2", bio: "Builds and debugs AI-native frontend systems in production.", followers: 10940 }, relatedThreads: [], trendingThreads: [] },
  insights: {
    summary: "Most helpers converge on deterministic keying and delayed client hydration for streamed segments.",
    keyAgreements: ["Hydration mismatch is tied to unstable keys.", "Client-only wrappers reduce mismatch risk.", "Streaming chunk boundaries must be deterministic."],
    openQuestions: [{ id: "oq-help-1", question: "Can suspense fallback state be normalized across server/client?", commentId: "tcom-help-5" }],
    topContributor: { userId: "u1", topCommentId: "tcom-help-6", excerpt: "Force deterministic IDs before stream rendering; hydration became stable immediately." },
    genealogy: {
      buildsOn: [{ id: "review-001", title: "45-day production review: Claude + retrieval workflow for creator teams", authorName: "Marcus Johnson", engagementCount: 741, category: "review" }],
      contradicts: [],
      canonical: { id: "news-001", title: "Open model safety benchmark update: what changed this week", authorName: "Emily Zhang", engagementCount: 892, category: "news" },
    },
  },
  categoryData: {
    problem: {
      tryingToDo: "Stream AI-generated section summaries into a threaded discussion page.",
      tried: [
        "Wrapped stream output in Suspense fallback",
        "Added dynamic import with ssr: false for markdown renderer",
        "Memoized render tree by message ID",
      ],
      stuck: "Hydration mismatch appears when markdown blocks contain code fences with delayed token streams.",
    },
    environment: ["Next.js 14", "React 18", "TypeScript", "Vercel", "Claude API"],
    solved: true,
    solutionCommentId: "tcom-help-6",
    reproducibilityCount: 37,
    diagnosticPath: [
      { label: "Validate deterministic key generation", state: "tried" },
      { label: "Normalize fallback markup shape", state: "tried" },
      { label: "Render markdown in client-only shell", state: "suggested" },
      { label: "Gate code block hydration until stream complete", state: "suggested" },
    ],
    similarSolvedThreads: [
      { id: "showcase-001", title: "Showcase: conversion-focused onboarding redesign", snippet: "Solved rendering drift by deferring interactive markup.", solveTime: "2h" },
      { id: "compare-001", title: "Claude vs GPT for creator operations in 2026", snippet: "Stabilized table keys to avoid hydration mismatch.", solveTime: "4h" },
    ],
  },
  qualityDimensions: { novelty: 65, verifiability: 89, actionability: 92, synthesis: 79 },
  alien: {
    updates: [
      { id: "u-help-1", byHandle: "@marcusdev", at: "2026-03-21T09:12:00.000Z", content: "Marked accepted solution and added reproducible snippet." },
    ],
    coAuthors: ["u2"],
    freshnessWarning: { lastUpdatedDaysAgo: 0, updateRequests: 1 },
    serendipity: [{ id: "review-001", title: "45-day production review: Claude + retrieval workflow for creator teams", authorName: "Marcus Johnson", engagementCount: 741, category: "review" }],
  },
};

export const helpThread: ThreadData = {
  ...baseThread,
  sidebar: buildSidebar(baseThread),
};

export const helpComments: ThreadComment[] = [
  {
    id: "tcom-help-1",
    threadId: "help-001",
    authorId: "u3",
    body: "Can you share a reduced repro with the markdown renderer and streamed chunk boundaries?",
    createdAt: "2026-03-20T09:12:00.000Z",
    upvotes: 21,
    downvotes: 0,
    intentTag: "question",
  },
  {
    id: "tcom-help-2",
    threadId: "help-001",
    authorId: "u2",
    body: "Yes — key detail is code fences arriving across multiple chunks. I’ll paste repro below.",
    createdAt: "2026-03-20T09:18:00.000Z",
    upvotes: 16,
    downvotes: 0,
    isOpReply: true,
    parentId: "tcom-help-1",
    intentTag: "resource",
  },
  {
    id: "tcom-help-3",
    threadId: "help-001",
    authorId: "u2",
    body: "```tsx\nconst id = nanoid();\nreturn <Markdown key={id}>{streamed}</Markdown>;\n```\nThis is current implementation.",
    createdAt: "2026-03-20T09:19:00.000Z",
    upvotes: 13,
    downvotes: 2,
    parentId: "tcom-help-2",
    intentTag: "resource",
  },
  {
    id: "tcom-help-4",
    threadId: "help-001",
    authorId: "u1",
    body: "That key generation is non-deterministic across server/client. Seed key from message id + stable segment index.",
    createdAt: "2026-03-20T09:28:00.000Z",
    upvotes: 52,
    downvotes: 0,
    parentId: "tcom-help-3",
    intentTag: "solution",
  },
  {
    id: "tcom-help-5",
    threadId: "help-001",
    authorId: "u4",
    body: "Also normalize suspense fallback markup to match first render shape exactly.",
    createdAt: "2026-03-20T09:35:00.000Z",
    upvotes: 39,
    downvotes: 1,
    intentTag: "implementation-note",
  },
  {
    id: "tcom-help-6",
    threadId: "help-001",
    authorId: "u1",
    body: "Accepted fix:\n```tsx\nconst key = `\${messageId}-\${segmentIndex}`;\nconst safe = useMemo(() => streamed.replace(/\\r\\n/g, \"\\n\"), [streamed]);\nreturn <Markdown key={key}>{safe}</Markdown>;\n```\nPlus defer code highlighting until stream end.",
    createdAt: "2026-03-20T09:42:00.000Z",
    upvotes: 88,
    downvotes: 0,
    isSolution: true,
    intentTag: "solution",
  },
  {
    id: "tcom-help-7",
    threadId: "help-001",
    authorId: "u5",
    body: "Confirmed — same pattern fixed our mismatch in a transcription app.",
    createdAt: "2026-03-20T10:00:00.000Z",
    upvotes: 31,
    downvotes: 0,
    parentId: "tcom-help-6",
    intentTag: "evidence",
  },
  {
    id: "tcom-help-8",
    threadId: "help-001",
    authorId: "u2",
    body: "Solved. Applying this in production now. Thanks all.",
    createdAt: "2026-03-20T10:14:00.000Z",
    upvotes: 24,
    downvotes: 0,
    isOpReply: true,
    parentId: "tcom-help-6",
    intentTag: "decision-proposal",
  },
];
